# Generated by Django 4.1.1 on 2022-09-30 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256)),
                ('description', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_question_text', models.CharField(default=None, max_length=256)),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_question_alternative_text', models.CharField(default=None, max_length=256)),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('survey_question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('survey_question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
                ('survey_question_alternative', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestionalternative')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
